strategy:
  type: copy
  pair: 'ETHUSD'
  target:
    driver: rubykube
    host: "http://www.devkube.com"
    name: John
    key: ""
    secret: ""
  sources:
    - driver: bitfinex
      host: ""
      name: Joe
      key: ""
      secret: ""
