strategy:
  type: copy
  target:
    driver: rubykube
    market: 'ETHUSD'
    host: "http://www.devkube.com"
    key: ""
    secret: ""
    rate_limit: 0.2
  sources:
    - driver: bitfaker
      market: 'tETHUSD'
      host: "api.bitfinex.com"
      key: ""
      secret: ""
      rate_limit: 0.2
#    - driver: bitfinex
#      market: 'tETHUSD'
#      host: "api.bitfinex.com"
#      key: ""
#      secret: ""
#      rate_limit: 0.2
